# Whisprd System Configuration

# Audio settings
audio:
  sample_rate: 48000
  channels: 1
  buffer_size: 24000  # 0.5 seconds at 48kHz
  device: null  # null = default device

# Whisper settings
whisper:
  model_size: "large"  # tiny, base, small, medium, large - using largest model for RTX 4070 Ti SUPER
  language: "en"
  beam_size: 5
  best_of: 5
  temperature: 0.0
  condition_on_previous_text: false
  initial_prompt: "The following is a dictation of clear speech without background music or noise."
  
  # GPU/CUDA settings
  use_cuda: true  # Enable CUDA GPU acceleration (auto-fallback to CPU if not available)
  cuda_device: 0  # CUDA device index (0 for first GPU)
  
  # Alternate prompt configuration
  alternate_prompts_file: null  # Path to YAML file with alternate prompts (e.g., "~/whisprd_prompts.yaml")
  use_alternate_prompts: false  # Enable to use prompts from alternate_prompts_file

# Whisprd settings
whisprd:
  # Hotkey to toggle dictation (Ctrl+Alt+D)
  toggle_hotkey: ["ctrl", "shift", "d"]
  
  # Command mode activation word
  command_mode_word: "computer"
  
  # Minimum confidence threshold for transcription (higher = more selective)
  confidence_threshold: 0.9
  
  # Auto-punctuation settings
  auto_punctuation: true
  sentence_end_words: ["period", "full stop", "dot"]
  comma_words: ["comma", "pause"]
  question_words: ["question mark", "question"]
  
  # Pause duration settings
  pause_duration: 1.5  # seconds of silence to trigger utterance boundary (longer pause for cleaner cuts)
  min_utterance_duration: 1.0  # minimum utterance length to transcribe (avoid short noise)
  overlap_duration: 0.2  # seconds to keep as overlap between utterances

# Voice commands mapping
commands:
  # Navigation commands
  "new line": "KEY_ENTER"
  "new paragraph": "KEY_ENTER,KEY_ENTER"
  "backspace": "KEY_BACKSPACE"
  "delete word": "KEY_CTRL+KEY_BACKSPACE"
  "delete line": "KEY_CTRL+KEY_A,KEY_DELETE"
  
  # Punctuation
  "period": "KEY_DOT"
  "comma": "KEY_COMMA"
  "question mark": "KEY_LEFTSHIFT+KEY_SLASH"
  "exclamation mark": "KEY_LEFTSHIFT+KEY_1"
  "semicolon": "KEY_SEMICOLON"
  "colon": "KEY_LEFTSHIFT+KEY_SEMICOLON"
  "open parenthesis": "KEY_LEFTSHIFT+KEY_9"
  "close parenthesis": "KEY_LEFTSHIFT+KEY_0"
  "open bracket": "KEY_LEFTBRACE"
  "close bracket": "KEY_RIGHTBRACE"
  "quote": "KEY_APOSTROPHE"
  "double quote": "KEY_LEFTSHIFT+KEY_APOSTROPHE"
  
  # Text formatting
  "capitalize": "KEY_CTRL+KEY_A,KEY_CTRL+KEY_U"
  "select all": "KEY_CTRL+KEY_A"
  "copy": "KEY_CTRL+KEY_C"
  "paste": "KEY_CTRL+KEY_V"
  "cut": "KEY_CTRL+KEY_X"
  "undo": "KEY_CTRL+KEY_Z"
  "redo": "KEY_CTRL+KEY_Y"
  
  # Special actions
  "stop dictation": "STOP_DICTATION"
  "start dictation": "START_DICTATION"
  "clear text": "KEY_CTRL+KEY_A,KEY_DELETE"

# Output settings
output:
  # Save transcriptions to file
  save_to_file: true
  transcript_file: "~/whisprd_transcript.txt"
  
  # Console output
  console_output: true
  
  # Keystroke injection
  inject_keystrokes: true

# Performance settings
performance:
  # Number of worker threads for transcription
  transcription_threads: 2
  
  # Audio buffer size in seconds
  audio_buffer_seconds: 1.0
  
  # Maximum transcription latency in seconds
  max_latency: 2.0
  
  # GPU memory management
  gpu_memory_fraction: 0.8  # Fraction of GPU memory to use (0.0-1.0)
  enable_memory_efficient_attention: true  # Use memory-efficient attention for large models 